### ISSUE TITLE
Recipe Function crafts null instead of invalidating recipe

### ISSUE THREAD

**Issue by Wolframme** [codetaylor/artisan-workstumps-1.12#1]
Hello, I'm having an issue with Artisan Workstumps actually crafting null when I want it to invalidate the recipe.

The idea is the recipe is only supposed to repair the tool when its a matching material, and this works when using a normal Artisan Worktable. The recipe is null when the ingot doesn't match up, and the recipe works when it does.

<img alt="" src="https://imgur.com/whjd439.png">

<img alt="" src="https://imgur.com/CbM9B83.png">

However when testing this with an Artisan Workstump the recipe still goes ahead with this, and the tool goes *poof*

<img alt="" src="https://imgur.com/jPabXLt.gif">

[repair.zs](https://gist.github.com/Wolframme/93415bd685830c8992fd9158c6a5b0c0#file-repair-zs-L411)

Pardon the mess that is my script, that is the function that returns null if nothing matches just for proof.

**Comment by codetaylor** [comment]
Thanks for the report!

Can you please reproduce this with a simpler script and vanilla items only?

**Comment by Wolframme** [comment]
Of course, sorry, I should have just done that.

Here is one I've tested working on a Blacksmith's Worktable, and tested to craft on the Workstump counterpart till it doesn't match and crafts null.

[null.zs](https://gist.github.com/Wolframme/0cd432bf9bbd4d3a0e043c829710790e)

**Comment by codetaylor** [comment]
Thank you. That is considerably easier to understand. 😄

**Comment by codetaylor** [comment]
Should be fixed in `1.12.2-1.1.3`

**Comment by Wolframme** [comment]
Thanks! Works now. Sorry about the insane wall of text that is my script.
